### ISSUE TITLE
Erro na v4.0.2 - Crítica de limite de 250 caracteres na tela Alterar Parâmetro

### ISSUE THREAD

**Issue by neijobson** [cgugovbr/mod-sei-eouv#12]
@danielcoelhocgu 

Na v4.0.2 alteraram o tipo da coluna de Valor Parâmetro por conta do tamanho novo de Token, mas esqueceram de alterar a crítica javascript na tela, que critica "Tamanho do campo excedido (máximo 250 caracteres)."

![image](https://github.com/cgugovbr/mod-sei-eouv/assets/49068090/93942a1e-d0c0-4c05-988c-e8b8c82aca0b)

**Comment by danielcoelhocgu** [comment]
Olá @neijobson. Obrigado pelo reporte. Realmente não percebi essa verificação.

Na verdade esse campo TOKEN não é para ser editado. Ele é gerado automaticamente pelo módulo a partir das credenciais fornecidas nos outros campos. Na próxima versão eu vou retirá-lo dessa lista de parâmetros.

Na versão do branch *dev* essa tela de parâmetros está mais "amigável", sendo um formulário de fato e não uma lista genérica de nome e valor. Ela já não contém o token. Nesse branch estamos fazendo alteraçõs substanciais na estrutura do código, por isso ainda não foi publicada, mas segue uma captura do formulário para você ter uma ideia:

![image](https://github.com/cgugovbr/mod-sei-eouv/assets/110624029/417e5d46-4b46-44d6-8b7b-a6071cef354a)

**Comment by neijobson** [comment]
@danielcoelhocgu 
Que bom que estão melhorando o módulo.
Levem o menu para a Administração geral do SEI, pois não é comum menu de parametrizações estar na raiz do SEI.

Além do Manual a seguir, que é complemento ao Manual de Desenvolvimento de Módulos em PDF do TRF4 e tem importante recurso de máquina local de desenvolvimento padrão: http://bit.ly/SEI_Manual_Padroes_Desenvolvimento_Modulos

Vejam os módulos da Anatel:
* https://github.com/anatelgovbr/mod-sei-peticionamento
* https://github.com/anatelgovbr/mod-sei-utilidades
* https://github.com/anatelgovbr/mod-sei-litigioso
* https://github.com/anatelgovbr/mod-sei-correios

Desenvolvemos módulos desde 2015 e seguimos bem rígidos boas práticas e padrões.

Ainda, avalie se tem algum problema aí na integração das Manifestações de Ouvidoria, pois falaram que o SEI não é adequado para importar esses processos porque deixa Público. Contudo, deixa pública SE O MÓDULO não tiver sido desenvolvido corretamente para gerar os documentos como Restrito.

**Comment by danielcoelhocgu** [comment]
Itens corrigidos no branch *dev*.
