### ISSUE TITLE
Revisar todos os arquivos para usar Terminador de Linha CRLF

### ISSUE THREAD

**Issue by neijobson** [cgugovbr/mod-sei-eouv#8]
@danielcoelhocgu

Vocês estão trabalhando o desenvolvimento provavelmente em Linux e os códigos do módulo estão todos com o terminador de linha do Unix (LF).
- Mas o padrão do SEI é o do Windows (CRLF).

Precisam revisar o projeto e converter todos os arquivos para CRLF.

![image](https://github.com/cgugovbr/mod-sei-eouv/assets/49068090/d91e1037-5864-48cf-b6fd-9c30e00db928)

**Comment by danielcoelhocgu** [comment]
Obrigado pelo alerta @neijobson. Inseri o arquivo `.gitattributes` para que o Git sempre use a terminação CRLF. A partir da próxima versão os arquivos do release já virão dessa forma.
