### ISSUE TITLE
Erro nas rotinas para salvar TOKEN - campo “de_valor_parametro” no banco com varchar pequeno

### ISSUE THREAD

**Issue by neijobson** [cgugovbr/mod-sei-eouv#9]
@danielcoelhocgu 

No momento do Agendamento executado para obter o TOKEN, tem erro. Os tokens retornados pelo webservice do Fala.BR está maior que o tamanho do campo “de_valor_parametro” na tabela “md_eouv_parametros”.

- O referido campo “de_valor_parametro” é criado pelo script do módulo como varchar(455) e os tokens retornados são maiores que isso.
- Alterei o campo “de_valor_parametro” no ambiente aqui de Homologação do SEI na Anatel para varchar(1000) e passou sem estouro.

Somente quando fiz o ajuste indicado pelo banco é que tudo funcionou ok. Assim, precisam revisar no script do SEI na linha 201, de "455" para "1000".

`Detalhes:
UPDATE md_eouv_parametros SET no_parametro=?, de_valor_parametro=? WHERE md_eouv_parametros.id_parametro=?

Bind:
0: s, TOKEN
1: s, TOKEN AQUI GRANDÃO QUE DÁ ERRO
2: i, 10

Trilha de Processamento:
0 /opt/appsei/infra/infra_php/InfraBD.php(210): InfraMySqli->executarSql('', Array)
1 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvParametroRN.php(54): InfraBD->alterar(Object(MdCguEouvParametroDTO))
2 /opt/appsei/infra/infra_php/InfraRN.php(151): MdCguEouvParametroRN->alterarParametroControlado(Object(MdCguEouvParametroDTO))
3 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(195): InfraRN->__call('', Array)
4 /opt/appsei/sei/web/modulos/cgu/mod-sei-eouv/rn/MdCguEouvAgendamentoRN.php(654): MdCguEouvAgendamentoRN->gravarParametroToken('')
5 /opt/appsei/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(664): MdCguEouvAgendamentoRN->executarImportacaoManifestacaoEOuv(Array)
6 /opt/appsei/infra/infra_php/formularios/infra_agendamento_tarefa_lista.php(46): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
7 /opt/appsei/infra/infra_php/InfraControlador.php(111): require_once('')
8 /opt/appsei/sei/web/controlador.php(1707): InfraControlador::processar('', Object(PaginaSEI), Object(SessaoSEI), Object(BancoSEI), Object(LogSEI), Object(CacheSEI), Object(AuditoriaSEI))
9 {main}`

**Comment by danielcoelhocgu** [comment]
Obrigado pelo reporte @neijobson. Realmente o tamanho do token do FalaBR aumentou de tamanho. Fiz a atualização do tipo da coluna no script de atualização e já sairá corrigido na próxima versão publicada.
